In [ ]:
import pandas as pd

In [5]:
df=pd.DataFrame(
    {
        "name":["cow" ,"cat ","dog","black","wscube"]
    }
)
df

     name
0     cow
1    cat
2     dog
3   black
4  wscube

In [6]:
from sklearn.preprocessing import LabelEncoder

In [10]:
le=LabelEncoder()
df["en_name"]=le.fit_transform(df["name"])

In [11]:
df

     name  en_name
0     cow        2
1    cat         1
2     dog        3
3   black        0
4  wscube        4

In [15]:
dataset=pd.read_csv(r'loan_dataset.csv')
dataset.head(3)

,Loan_ID,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Gender,Married,Dependents,Education,Self_Employed,Property_Area,Loan_Status
0,LN0001,17795.0,4000.0,300.0,360.0,0.0,Male,Yes,2,Not Graduate,NaN,Semiurban,N
1,LN0002,2860.0,0.0,100.0,NaN,NaN,NaN,NaN,0,Not Graduate,No,Semiurban,N
2,LN0003,7390.0,NaN,150.0,180.0,NaN,Male,NaN,1,Graduate,Yes,Rural,Y

In [18]:
la=LabelEncoder()
dataset["Education"]=la.fit_transform(dataset["Education"])

In [19]:
dataset["Education"]

0     1
1     1
2     0
3     1
4     0
5     0
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    0
15    1
16    1
17    0
18    1
19    0
20    0
Name: Education, dtype: int64

#ordinal encoding