In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv(r'loan_dataset.csv')

In [3]:
dataset.isnull().sum()

Loan_ID               0
ApplicantIncome       0
CoapplicantIncome     7
LoanAmount            2
Loan_Amount_Term      5
Credit_History        5
Gender               10
Married              11
Dependents            7
Education             0
Self_Employed         7
Property_Area         0
Loan_Status           0
dtype: int64

In [4]:
dataset.head(16)

,Loan_ID,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Gender,Married,Dependents,Education,Self_Employed,Property_Area,Loan_Status
0,LN0001,17795.0,4000.0,300.0,360.0,0.0,Male,Yes,2,Not Graduate,NaN,Semiurban,N
1,LN0002,2860.0,0.0,100.0,NaN,NaN,NaN,NaN,0,Not Graduate,No,Semiurban,N
2,LN0003,7390.0,NaN,150.0,180.0,NaN,Male,NaN,1,Graduate,Yes,Rural,Y
3,LN0004,23575.0,1500.0,250.0,NaN,0.0,Male,No,1,Not Graduate,Yes,Urban,Y
4,LN0005,13964.0,4000.0,100.0,NaN,NaN,NaN,Yes,3+,Graduate,Yes,Urban,N
5,LN0006,13284.0,NaN,250.0,180.0,1.0,NaN,NaN,NaN,Graduate,NaN,Rural,Y
6,LN0007,24118.0,0.0,NaN,180.0,0.0,NaN,No,2,Not Graduate,No,Urban,Y
7,LN0008,8265.0,0.0,150.0,180.0,1.0,Male,NaN,0,Not Graduate,Yes,Rural,Y
8,LN0009,18850.0,2500.0,150.0,180.0,1.0,NaN,NaN,3+,Not Graduate,Yes,Rural,N
9,LN0010,6426.0,2500.0,100.0,180.0,0.0,NaN,Yes,NaN,Not Graduate,Yes,Semiurban,N
10,LN0011,23962.0,1500.0,150.0,NaN,NaN,Male,NaN,3+,Not Graduate,NaN,Rural,Y
11,LN0012,16423.0,NaN,300.0,180.0,1.0,NaN,Yes,NaN,Not Graduate,NaN,Semiurban,N
12,LN0013,13363.0,NaN,150.0,360.0,0.0,Male,NaN,NaN,Not Graduate,No,Urban,N
13,LN0014,18023.0,2500.0,250.0,120.0,1.0,Female,No,2,Not Graduate,NaN,Urban,N
14,LN0015,10322.0,NaN,250.0,180.0,1.0,NaN,NaN,NaN,Graduate,Yes,Urban,N
15,LN0016,3685.0,NaN,250.0,180.0,1.0,Female,Yes,3+,Not Graduate,No,Urban,N

In [5]:
dataset['Gender'].fillna(dataset['Gender'].mode()[0],inplace=True)
dataset['Married'].fillna(dataset['Married'].mode()[0],inplace=True)

C:\Users\layap\AppData\Local\Temp\ipykernel_2684\3689637743.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Gender'].fillna(dataset['Gender'].mode()[0],inplace=True)
C:\Users\layap\AppData\Local\Temp\ipykernel_2684\3689637743.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Married'].fillna(dataset['Married'].mode()[0],inplace=True)

In [6]:
en_data=dataset[['Gender','Married']]

In [7]:
pd.get_dummies(en_data).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Gender_Female  21 non-null     bool
 1   Gender_Male    21 non-null     bool
 2   Married_No     21 non-null     bool
 3   Married_Yes    21 non-null     bool
dtypes: bool(4)
memory usage: 212.0 bytes

#using sciket-learn

In [8]:
from sklearn.preprocessing import OneHotEncoder

In [12]:
ohe=OneHotEncoder(drop='first')
ar=ohe.fit_transform(en_data).toarray()
pd.DataFrame(ar,columns=['Gender_Male','Married_Yes'])

    Gender_Male  Married_Yes
0           1.0          1.0
1           1.0          1.0
2           1.0          1.0
3           1.0          0.0
4           1.0          1.0
5           1.0          1.0
6           1.0          0.0
7           1.0          1.0
8           1.0          1.0
9           1.0          1.0
10          1.0          1.0
11          1.0          1.0
12          1.0          1.0
13          0.0          0.0
14          1.0          1.0
15          0.0          1.0
16          1.0          1.0
17          1.0          0.0
18          1.0          1.0
19          0.0          1.0
20          1.0          1.0

In [13]:
en_data

    Gender Married
0     Male     Yes
1     Male     Yes
2     Male     Yes
3     Male      No
4     Male     Yes
5     Male     Yes
6     Male      No
7     Male     Yes
8     Male     Yes
9     Male     Yes
10    Male     Yes
11    Male     Yes
12    Male     Yes
13  Female      No
14    Male     Yes
15  Female     Yes
16    Male     Yes
17    Male      No
18    Male     Yes
19  Female     Yes
20    Male     Yes